# Generated by Django 4.1.2 on 2022-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_opiniones', '0004_opinion_delete_configuracion_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
