# Generated by Django 4.1.2 on 2022-11-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_opiniones', '0005_alter_opinion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='breve_opinion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='firma',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinion_detallada',
            field=models.CharField(max_length=3000),
        ),
    ]
